### PR TITLE
[15] Go Back to a previous page functionality

### PR DESCRIPTION
**Pull request by valorious**

### CODE REVIEW

**Comment by calebdre** [comment]
Pull upstream for the latest version. I tried to test and i'm not seeing this feature in the simulation

**Comment by valorious** [comment]
Fixed some bugs with this. There are still bugs with the edge case where a student clicks the 'change my choice' button and then clicks another 'change my choice' button while on that page. I can try to fix that or I can just disable the buttons when they are on a page they went back to.

**Comment by calebdre** [comment]
It would be best to disable the buttons for now if it's easier

**Comment by valorious** [comment]
I decided to hide the buttons because I thought that would be slightly better than just showing them as disabled from a usability standpoint.

**Pull request merged**
