### PR TITLE
#23 Added minimum choices reached button functionality in PageEngine/Page…

### PR DESCRIPTION
**Pull request by mparq**
…Renderer.

### CODE REVIEW

**Comment by calebdre** [comment]
There has to be a better way. The Engine should be in charge of all interactions.  
Only append the button in the Renderer and place the event listener in the Engine. There has to be a better way. The Engine should be in charge of all interactions between the page and the user.  

Also make sure to add the button before the new page is transitioned in

**Comment by mparq** [comment]
Hmmm okay I'll look into it. The reason I had to put that button after the transition is because the button is being appended to $(".screen"), and it doesn't look like the other elements are being appended to it until transition is called. Actually, yes the only reason I didn't attach the listener in the Engine was because I wasn't sure how to get the minimum_page but I think I figured it out. I have a TA meeting right now, but I'll commit my changes in about an hour.

**Comment by mparq** [comment]
I've separated the adding of listener from the Renderer. Also fixed a bug that resurfaced where the visits weren't incrementing on popup windows until a refresh. The way I did this was basically to "change page" back to the current page whenever a popup window is clicked, so the popup window itself is not added to the page chain, the page is just reloaded in the background. 

What specifically did you mean when you said the button had to be added before the new page was transitioned in?

**Comment by calebdre** [comment]
I meant after! But it's all fine now

**Pull request merged**
